services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  django:
    build: .  # because Dockerfile is now in current dir or use ./app if needed
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py tailwind install &&
      python manage.py tailwind build &&
      python manage.py runserver 0.0.0.0:8000" &&
      python Ai_test.py
#      python manage.py sync_hubspot
#      TODO: Figure out file path when deployed
#      0 0 * * * cd /path/to/your/project && /path/to/your/virtualenv/bin/python manage.py sync_hubspot
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      EMAIL_BACKEND: django.core.mail.backends.console.EmailBackend
    volumes:
      - .:/app  # mount the whole current dir as /app inside the container
    depends_on:
      - postgres

volumes:
  pgdata:
