CREATE USER readonly_user WITH PASSWORD 'readonly_pw';
GRANT CONNECT ON DATABASE tracker_AMBAC TO readonly_user;
GRANT USAGE ON SCHEMA public TO readonly_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO readonly_user;